name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # استخدام أداة جيت هاب الرسمية لإنشاء وضبط الـ Gradle Wrapper تلقائياً وبأعلى توافق
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-root-directory: FacebookPhotoFixer
        gradle-version: 8.7

    - name: Build Debug APK
      run: |
        cd FacebookPhotoFixer
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FacebookPhotoFixer-APK
        path: |
          FacebookPhotoFixer/app/build/outputs/apk/debug/*.apk
